#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the staircase function below.
def staircase(n):
    i = 0
    for i in range(n):
        bosluk = ((n-1)*(' '))
        kare = ((i+1)*('#'))
        print(bosluk+kare)
        i = i + 1
        n = n - 1
if __name__ == '__main__':
    n = int(input())

    staircase(n)
