#!/bin/python3
import math
import os
import random
import re
import sys

# Complete the rotLeft function below.
def rotLeft(a, d):
    new_arr = []
    for i in range(len(a)-d): 
        new_arr.append(a[d+i]) 
    for i in range(0,len(a)-len(new_arr)):
        new_arr.append(a[i])
    return new_arr
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nd = input().split()

    n = int(nd[0])

    d = int(nd[1])

    a = list(map(int, input().rstrip().split()))

    result = rotLeft(a, d)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
